exception 3exception_invalid2;

